switched to envsubst

diff --git a/content/etc/s6-overlay/s6-rc.d/init-dockerize/run b/content/etc/s6-overlay/s6-rc.d/init-dockerize/run
--- a/content/etc/s6-overlay/s6-rc.d/init-dockerize/run
+++ b/content/etc/s6-overlay/s6-rc.d/init-dockerize/run
@@ -1,8 +1,27 @@
 #!/command/with-contenv bash
 
-/usr/local/bin/dockerize \
-  -template /etc/postfix/template/mysql-virtual-alias-maps.cf.templ:/etc/postfix/mysql-virtual-alias-maps.cf \
-  -template /etc/postfix/template/mysql-virtual-mailbox-domains.cf.templ:/etc/postfix/mysql-virtual-mailbox-domains.cf \
-  -template /etc/postfix/template/mysql-virtual-mailbox-maps.cf.templ:/etc/postfix/mysql-virtual-mailbox-maps.cf \
-  -template /etc/postfix/template/mysql-virtual-mailbox-senders.cf.templ:/etc/postfix/mysql-virtual-mailbox-senders.cf \
-  -template /etc/postfix/template/mysql-recipient-access.cf.templ:/etc/postfix/mysql-recipient-access.cf
+set -e
+
+DB_USER=${DB_USER:-}
+DB_PASSWORD=${DB_PASSWORD:-}
+DB_HOST=${DB_HOST:-}
+DB_DATABASE=${DB_DATABASE:-}
+
+if [ -z "${DB_USER}" ] || [ -z "${DB_PASSWORD}" ] || [ -z "${DB_HOST}" ] || [ -z "${DB_DATABASE}" ]; then
+  echo "ERROR: DB_USER, DB_PASSWORD, DB_HOST, and DB_DATABASE must be set"
+  exit 1
+fi
+
+render_template() {
+  src="$1"
+  dst="$2"
+
+  envsubst < "${src}" > "${dst}"
+}
+
+echo "Rendering postfix SQL map templates"
+render_template /etc/postfix/template/mysql-virtual-alias-maps.cf.templ /etc/postfix/mysql-virtual-alias-maps.cf
+render_template /etc/postfix/template/mysql-virtual-mailbox-domains.cf.templ /etc/postfix/mysql-virtual-mailbox-domains.cf
+render_template /etc/postfix/template/mysql-virtual-mailbox-maps.cf.templ /etc/postfix/mysql-virtual-mailbox-maps.cf
+render_template /etc/postfix/template/mysql-virtual-mailbox-senders.cf.templ /etc/postfix/mysql-virtual-mailbox-senders.cf
+render_template /etc/postfix/template/mysql-recipient-access.cf.templ /etc/postfix/mysql-recipient-access.cf
